version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./registry.conf:/etc/nginx/conf.d/registry.conf:ro
      - ./nginx-selfsigned.pem:/etc/ssl/certs/nginx-selfsigned.pem
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key

  registry:
    image: registry:2.8
    container_name: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
      - ./auth:/auth
